### ISSUE TITLE
Call to undefined method Omeka\Api\Representation\ValueRepresentation::valueAnnotation()

### ISSUE THREAD

**Issue by deemoss** [omeka-s-themes/foundation-s#44]
I get the following error when clicking on an item:

`Call to undefined method Omeka\Api\Representation\ValueRepresentation::valueAnnotation()`

```
Details:

Error: Call to undefined method Omeka\Api\Representation\ValueRepresentation::valueAnnotation() in /home1/reposit4/public_html/omekas/themes/foundation/view/common/resource-values.phtml:38
Stack trace:
#0 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include()
#1 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, Array)
#2 /home1/reposit4/public_html/omekas/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(471): Laminas\View\Helper\Partial->__invoke('common/resource...', Array)
#3 /home1/reposit4/public_html/omekas/themes/foundation/view/omeka/site/item/show.phtml(109): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayValues()
#4 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/home1/reposit4...')
#5 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#6 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#7 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#8 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#9 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#10 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#11 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#12 /home1/reposit4/public_html/omekas/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#13 /home1/reposit4/public_html/omekas/index.php(21): Laminas\Mvc\Application->run()
#14 {main}
```
I am using:
Omaka-S v3.1.2
Foundation v1.2.3

Screenshot:
[https://www.dropbox.com/s/e9fkomnx1c1fkss/omekas1.png?dl=0](url)

Thanks!

**Comment by kimisgold** [comment]
This should be fixed as of Foundation S version v1.2.4 with Omeka S v3.2.0^.
